// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruyenAnime.Data;

#nullable disable

namespace TruyenAnime.Migrations
{
    [DbContext(typeof(TruyenAnimeDbContext))]
    partial class TruyenAnimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TruyenAnime.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("TruyenAnime.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shounen"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shoujo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seinen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Josei"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kodomo"
                        });
                });

            modelBuilder.Entity("TruyenAnime.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("TruyenAnime.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TruyenAnime.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TruyenAnime.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHotDeal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNewArrival")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Gege Akutami",
                            CategoryId = 1,
                            Description = "Itadori Yuji là một học sinh cấp Ba sở hữu năng lực thể chất phi thường. Hằng ngày cậu thường tới bệnh viện chăm người ông đang ốm liệt giường. Nhưng một ngày nọ, phong ấn của “chú vật” vốn ngủ yên trong trường bị phá giải, quái vật xuất hiện. Để cứu hai anh chị khóa trên đang gặp nguy hiểm, Itadori đã xông vào trường và...",
                            ImageUrl = "https://product.hstatic.net/200000343865/product/chu-thuat-hoi-chien---tap-1_6d3f94c0ed3e4253baa722e759fe2eaa_master.jpg",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "Chú thuật hồi chiến - Tập 1",
                            Price = 27000m,
                            PublishYear = 2020,
                            Publisher = "NXB Kim Đồng",
                            Size = "13x18cm",
                            Stock = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Tomohito Oda",
                            CategoryId = 2,
                            Description = "\"Chứng rối loạn giao tiếp xã hội là việc cảm thấy khó khăn khi tương tác với người khác.\nNó còn dùng để chỉ những người ít hoặc không có kĩ năng giao tiếp.\"\nNhững người mắc phải chứng này chỉ sợ nói chuyện, chứ kì thực họ có rất nhiều điều muốn nói. Vậy phải làm sao để họ có thể giao tiếp trong cuộc sống thường ngày...?",
                            ImageUrl = "https://product.hstatic.net/200000343865/product/1_202f1ff8a90946b5ba433792cc267064_07fb27d9a3094122b7818c8c94983408_master.jpg",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "Komi - Nữ thần sợ giao tiếp - Tập 1",
                            Price = 22500m,
                            PublishYear = 2021,
                            Publisher = "NXB Trẻ",
                            Size = "13x18cm",
                            Stock = 0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Makoto Shinkai",
                            CategoryId = 3,
                            Description = "Giới thiệu sách: TOP 100 BEST SELLER - 5cm/s không chỉ là vận tốc của những cánh anh đào rơi, mà còn là vận tốc khi chúng ta lặng lẽ bước qua đời nhau, đánh mất bao cảm xúc thiết tha nhất của tình yêu.",
                            ImageUrl = "https://product.hstatic.net/200000287623/product/5cm_5f3b4ebe155b4d6491c244b8623657b5_master.jpg",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "5 Centimet Trên Giây",
                            Price = 48750m,
                            PublishYear = 2019,
                            Publisher = "NXB Văn Học",
                            Size = "14.5x20.5cm",
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            Author = "Tomoko Ninomiya",
                            CategoryId = 3,
                            Description = "Chiaki Shinichi là một sinh viên tài năng của nhạc viện nhưng chẳng có cơ hội phô diễn hết năng lực. Trong quá khứ cậu từng gặp ám ảnh tâm lý nên đã định từ bỏ ước mơ làm nhạc trưởng.\nNgày nọ, nghe thấy tiếng nhạc tuyệt vời bên tai, Chiaki tỉnh giấc và trông thấy cô nàng Nodame đang chơi piano giữa đống rác chất chồng…!? Cô là thiên tài hay kẻ kì quặc? Đó là khúc nhạc định mệnh đầu tiên dẫn dắt Chiaki đến với thứ âm nhạc mới mà cậu sẽ tạo nên cùng những người bạn kì lạ tại trường nhạc!",
                            ImageUrl = "https://product.hstatic.net/200000287623/product/nodame_cantabile_1_manga_bia_1_400eb59146564bbf9b10212b69f0e37a_master.png",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "Nodame Cantabile - Khúc Ngẫu Hứng Của Nodame - 1",
                            Price = 101200m,
                            PublishYear = 2022,
                            Publisher = "NXB Nhạc Việt",
                            Size = "14x21cm",
                            Stock = 0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Akira Toriyama",
                            CategoryId = 4,
                            Description = "Mặt trời lại mọc trên ngôi làng Penguin ~\nMảnh đất của những chuyên gia tấu hài!!\nNơi mà ai cũng điên khùng theo một cách riêng...\nĐừng cố lí giải vì mọi thứ ở đây đều không theo một quy luật nào!",
                            ImageUrl = "https://product.hstatic.net/200000343865/product/1_69cfc243af404c3d8270011f76a44164_master.jpg",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "Dr.SLUMP Ultimate Edition - Tập 1",
                            Price = 54000m,
                            PublishYear = 2023,
                            Publisher = "NXB Kim Đồng",
                            Size = "13x18cm",
                            Stock = 0
                        },
                        new
                        {
                            Id = 6,
                            Author = "Akumi Agitogi",
                            CategoryId = 3,
                            Description = "Nguyện ước… chỉ là niềm “hạnh phúc” nhỏ nhoi…\nSaimori Miyo sinh ra trong một gia đình sở hữu siêu năng nhưng lại không được thừa hưởng sức mạnh ấy.\nĐứa em gái cùng cha khác mẹ đã thức tỉnh năng lực của Miyo đối xử với cô như kẻ hầu người hạ, cha cũng chẳng yêu thương. Miyo không khác gì một đứa con gái không ai cần đến.\nCậu bạn thanh mai trúc mã cũng là người duy nhất luôn đứng về phía Miyo lại sẽ kết hôn với cô em gái cùng cha khác mẹ kia để kế nghiệp nhà vợ...\nMiyo trở thành kẻ ngáng đường và bị đem gả vào gia tộc Kudou, cho một kẻ nổi danh lạnh lùng tàn nhẫn…",
                            ImageUrl = "https://product.hstatic.net/200000343865/product/1--manga_46fb6583acf548a09c5357f04cfeca81_71bbec2087ef48378f6e991b6fca9cb9_master.jpg",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "Hôn nhân hạnh phúc của tôi - Tập 1",
                            Price = 45000m,
                            PublishYear = 2024,
                            Publisher = "NXB Phụ Nữ",
                            Size = "14x20cm",
                            Stock = 0
                        },
                        new
                        {
                            Id = 7,
                            Author = "Kouji Miura",
                            CategoryId = 1,
                            Description = "Inomata Taiki, thành viên câu lạc bộ cầu lông, mê chị Kano Chinatsu bên câu lạc bộ bóng rổ nữ như điếu đổ. Cậu bị thu hút bởi hình ảnh Chinatsu luôn chăm chỉ luyện tập một mình. Ngày nọ, một tình huống bất ngờ đã xảy ra. Quãng đường trước mắt còn xa xôi, song chí hướng của cả hai lại gần không ngờ tới. Từ đó, câu chuyện tình yêu tuổi thanh xuân ngọt ngào bắt đầu chớm nở.",
                            ImageUrl = "https://product.hstatic.net/200000343865/product/bluebox_tap-8_bia_f39eaafbe870416f974a189487ed4f97_master.jpg",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "Blue Box - Tập 8",
                            Price = 36000m,
                            PublishYear = 2024,
                            Publisher = "NXB Trẻ",
                            Size = "13x18cm",
                            Stock = 0
                        },
                        new
                        {
                            Id = 8,
                            Author = "Hiromu Arakawa",
                            CategoryId = 1,
                            Description = "Trong thế giới của những giả kim thuật sư, có một tồn tại đã đi vào huyền thoại và trở thành ước mơ bất cứ ai cũng ao khát - đó chính là \"Hòn đá Triết gia\".",
                            ImageUrl = "https://product.hstatic.net/200000343865/product/1_e43e42b5db6d4d41a9ba1ee351fc2120.jpg",
                            IsBestSeller = false,
                            IsHotDeal = false,
                            IsNewArrival = false,
                            Name = "Fullmetal Alchemist - Cang giả kim thuật sư",
                            Price = 22000m,
                            PublishYear = 2020,
                            Publisher = "NXB Kim Đồng",
                            Size = "13x18cm",
                            Stock = 0
                        });
                });

            modelBuilder.Entity("TruyenAnime.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Truyện hay lắm, nét vẽ đẹp, cốt truyện cuốn hút.",
                            CreatedAt = new DateTime(2025, 6, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minh@example.com",
                            ProductId = 1,
                            Rating = 5,
                            Username = "Minh"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Rất ý nghĩa, nhân vật chính dễ thương.",
                            CreatedAt = new DateTime(2025, 6, 17, 15, 1, 0, 0, DateTimeKind.Unspecified),
                            Email = "linh@example.com",
                            ProductId = 2,
                            Rating = 4,
                            Username = "Linh"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Nội dung ổn nhưng in hơi mờ.",
                            CreatedAt = new DateTime(2025, 6, 17, 15, 2, 0, 0, DateTimeKind.Unspecified),
                            Email = "hai@example.com",
                            ProductId = 1,
                            Rating = 3,
                            Username = "Hải"
                        });
                });

            modelBuilder.Entity("TruyenAnime.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TruyenAnime.Models.Order", b =>
                {
                    b.HasOne("TruyenAnime.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruyenAnime.Models.OrderDetail", b =>
                {
                    b.HasOne("TruyenAnime.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenAnime.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TruyenAnime.Models.Product", b =>
                {
                    b.HasOne("TruyenAnime.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TruyenAnime.Models.Review", b =>
                {
                    b.HasOne("TruyenAnime.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruyenAnime.Models.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TruyenAnime.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TruyenAnime.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("TruyenAnime.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TruyenAnime.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
